//DELETE  http://localhost:8080/users/

//GET http://localhost:8080/users


//POST http://localhost:8080/users HTTP/1.1
//Content-Type: application/json
//
//{
//  "firstName": "John",
//  "lastName": "Doe",
//  "age": 30,
//  "email": "test",
//  "phone": "123-456-7890",
//  "JobTitle": "Software Engineer",
//  "Experience": "5 years",
//  "Education": "Bachelors",
//  "password": "123456"
//}




//PUT  http://localhost:8080/users/65cd2803060fd9ded17e39db HTTP/1.1
//Content-Type: application/json
//
//{
//  "firstName": "Thomas",
//  "lastName": "the Train",
//  "age": 80,
//  "email": "test@gmail.com",
//  "phone": "N/A",
//  "JobTitle": "Mechanical Engineer",
//  "Experience": "90 years",
//  "Education": "Bachelors",
//  "password": "24689"
//}


//DELETE http://localhost:8080/applications/65cede8ac567cad094e6447a

//POST  http://localhost:8080/applications/65cd2b90e6786183a3d93655 HTTP/1.1
//Content-Type: application/json
//
//{
//  "Job": "Web Developer",
//  "Company": "dOTerra",
//  "Location": "Lehi, UT",
//  "Salary": "120000",
//  "Benefits": "Health, Dental, Vision, 401k",
//  "Requirements": "Bachelor's Degree in Computer Science",
//  "Experience": "4 years",
//  "Skills": "Java, Python, C++, HTML, CSS, JavaScript, React, Angular, AWS, C#, PHP",
//  "Description": "Develop software for Google's products and services",
//  "website": "www.doterra.com",
//  "interviewDate": "2024-02-12",
//  "interviewTime": "10:00 AM",
//  "applicationStatus": "Pending",
//  "interviewStatus": "Pending",
//  "offerStatus": "Pending",
//  "interviewFeedback": "N/A",
//  "owner": "65c53b94eec742a374429fca"
//}


PUT http://localhost:8080/applications/65cede8ac567cad094e6447a HTTP/1.1
Content-Type: application/json

{
  "Job": "Mobile Developer",
  "Company": "X",
  "Location": "San Francisco, CA",
  "Salary": "100000",
  "Benefits": "Health, Dental, Vision, 401k",
  "Requirements": "Bachelor's Degree in Computer Science",
  "Experience": "3 years",
  "Skills": "swift, objective-c, java, kotlin, android, ios, mobile development, software development",
  "Description": "Develop Mobile software for X services and applications",
  "website": "www.X.com",
  "interviewDate": "2019-02-15",
  "interviewTime": "10:00 AM",
  "applicationStatus": "Pending",
  "interviewStatus": "Pending",
  "offerStatus": "Pending",
  "interviewFeedback": "N/A"
}


