GET http://localhost:8080/users

//PUT http://localhost:8080/users/65c58edd61ba1f7c938394a5 HTTP/1.1
//Content-Type: application/json
//
//{
//  "firstName": "Ana",
//  "lastName": "Maldonado",
//  "age": 27,
//  "email": "test@gmail.com",
//  "phone": "123-456-7890",
//  "JobTitle": "UI/UX Designer",
//  "Experience": "4 years",
//  "Education": "Bachelors Degree",
//  "password": "4444449"
//}
//
